spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/siljeon
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create은 실행할 때마다 데이터를 다시 생성하고 drop함 / none은 넣어놓은 데이터를 계속 볼 수 있음
    properties:
      hibernate:
#        show_sql: true  얘는 System.out으로 출력하는 애 -> 로거로만 출력하기
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace #로그에 찍히는 쿼리에서 '?' 파라미터가 누구인지 알려줌